#!/bin/bash

psql -U postgres_user -d postgres_cdc <<EOF
CREATE USER debezium_user WITH PASSWORD 'debezium_password';
CREATE SCHEMA IF NOT EXISTS DEBEZIUM;
GRANT USAGE, CREATE ON SCHEMA DEBEZIUM TO debezium_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DEBEZIUM TO debezium_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA DEBEZIUM GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO debezium_user;
GRANT USAGE ON SCHEMA public TO debezium_user;
EOF
